language: python

jobs:
  include:
    - os: osx
      language: shell
      python: 3.6

install:
  - git clone https://github.com/spack/spack.git
  - . spack/share/spack/setup-env.sh
  - spack install glib

