language: python

jobs:
  include:
    - os: osx
      language: shell
      python: 3.6

install:
  - git clone --branch topic-emacsMoreDeps https://github.com/ax3l/spack.git
  - . spack/share/spack/setup-env.sh
  - spack install emacs

